apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: solr
spec:
  solrAddressability:
    external:
      domainName: YOUR_DOMAIN_NAME
      method: Ingress
      useExternalAddress: true
  customSolrKubeOptions:
    podOptions:
      resources:
        limits:
          memory: 3Gi
          cpu: 2000m
        requests:
          cpu: 700m
          memory: 3Gi
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
      reclaimPolicy: Delete
  replicas: 3
  solrImage:
    repository: entando/entando-solr
    tag: "8"
  solrJavaMem: -Xms2048M -Xmx2048M
  updateStrategy:
    method: StatefulSet
  zookeeperRef:
    provided:
      chroot: /explore
      image:
        pullPolicy: IfNotPresent
        repository: pravega/zookeeper
        tag: 0.2.13
      persistence:
        reclaimPolicy: Delete
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      replicas: 3
      zookeeperPodPolicy:
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
